const tg=window.Telegram?.WebApp;const state={user:null,infrastructure:[],packages:[]};
const I18N={en:{buy:"SUPPORT MISSION",completed:"COMPLETED",funding:"FUNDING",locked:"LOCKED"},uk:{buy:"ПІДТРИМАТИ МІСІЮ",completed:"ЗАВЕРШЕНО",funding:"ФІНАНСУВАННЯ",locked:"ЗАБЛОКОВАНО"},ja:{buy:"ミッションを支援",completed:"完了",funding:"資金調達中",locked:"ロック"}};
function getLanguage(){const c=tg?.initDataUnsafe?.user?.language_code||navigator.language||"en";return c.startsWith("uk")?"uk":c.startsWith("ja")?"ja":"en"}const language=getLanguage();function t(k){return I18N[language]?.[k]||I18N.en[k]||k}
function initData(){return tg?.initData||""}
async function api(endpoint,options={}){const headers={"Content-Type":"application/json","X-Telegram-Init-Data":initData(),...(options.headers||{})};const r=await fetch(endpoint,{...options,headers});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.detail||"API error")}return r.json()}
function pct(m){const a=Number(m.total_funding_required_usd);return a?Math.min(100,Number(m.current_funding_usd)/a*100):0}
function farmPct(){const req=state.infrastructure.reduce((s,m)=>s+Number(m.total_funding_required_usd),0),cur=state.infrastructure.reduce((s,m)=>s+Number(m.current_funding_usd),0);return req?Math.round(cur/req*100):0}
function renderZones(){for(const z of ["energy","pools","filtration","drying"]){const ms=state.infrastructure.filter(m=>m.zone===z),req=ms.reduce((s,m)=>s+Number(m.total_funding_required_usd),0),cur=ms.reduce((s,m)=>s+Number(m.current_funding_usd),0),p=req?Math.min(100,cur/req*100):0,e=document.getElementById("zone-"+z);e.classList.remove("funding","completed");if(p>=100)e.classList.add("completed");else if(p>0)e.classList.add("funding");e.querySelector(".zone-progress span").style.width=p+"%"}}
function renderInfrastructure(){const c=document.getElementById("modulesList");c.innerHTML="";for(const m of state.infrastructure){const d=document.createElement("div");d.className="module";d.innerHTML=`<div class="module-header"><div class="module-name">${esc(m.module_name)}</div><div class="module-status ${m.status}">${t(m.status)}</div></div><div class="module-meta"><span>${esc(m.zone.toUpperCase())}</span><span>$${num(m.current_funding_usd)} / $${num(m.total_funding_required_usd)}</span></div><div class="module-bar"><span style="width:${pct(m)}%"></span></div>`;c.appendChild(d)}}
function renderPackages(){const c=document.getElementById("packagesList");c.innerHTML="";for(const p of state.packages){const d=document.createElement("div");d.className="support-card";d.innerHTML=`<h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div>₴${num(p.price_uah)} &nbsp;//&nbsp; ${num(p.price_usdt)} USDT</div><button class="buy-button" data-id="${p.id}">${t("buy")}</button>`;c.appendChild(d)}document.querySelectorAll(".buy-button").forEach(b=>b.onclick=()=>purchase(Number(b.dataset.id)))}
async function purchase(id){const p=state.packages.find(x=>x.id===id);if(!p)return;const crypto=confirm("Use Crypto Pay simulation?\n\nOK = USDT\nCancel = Monobank / UAH");const currency=crypto?"USDT":"UAH",amount=crypto?p.price_usdt:p.price_uah;try{const r=await api("/api/payments/create",{method:"POST",body:JSON.stringify({amount,currency,purpose:"Drone Delivery Pack"})});if(tg?.showAlert)tg.showAlert(`Payment created: ${r.status}`);else alert(`Payment created: ${r.status}`)}catch(e){if(tg?.showAlert)tg.showAlert(e.message);else alert(e.message)}}
function num(v){return Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function render(){document.getElementById("username").textContent=state.user.username?"@"+state.user.username:"USER "+state.user.telegram_id;document.getElementById("balance").textContent="$"+num(state.user.balance_crypto);document.getElementById("farmStatus").textContent=farmPct()+"%";renderZones();renderInfrastructure();renderPackages()}
async function boot(){if(tg){tg.ready();tg.expand();tg.setHeaderColor?.("#05070b");tg.setBackgroundColor?.("#05070b")}try{state.user=await api("/api/auth",{method:"POST"});state.infrastructure=await api("/api/infrastructure");state.packages=await api("/api/support-packages");render()}catch(e){document.body.innerHTML+=`<div style="position:fixed;inset:0;display:grid;place-items:center;background:#05070b;color:#ff3158;font-family:monospace;padding:30px;text-align:center">TELEGRAM AUTHENTICATION ERROR<br><br>${esc(e.message)}</div>`}}boot();